# # #
# Base Dockerfile for Ruby applications
# # #

FROM ubuntu:trusty
ENV DEBIAN_FRONTEND noninteractive

# Ensure Locale
RUN apt-get -y update
RUN dpkg-reconfigure locales && \
  locale-gen en_US.UTF-8 && \
  /usr/sbin/update-locale LANG=en_US.UTF-8
ENV LC_ALL en_US.UTF-8

# Packages
RUN apt-get -y update
RUN apt-get -y install wget build-essential git

# Ruby dependencies
RUN apt-get -y install <%= packages.sort.join " " %>

# Install ruby-install
RUN cd /tmp &&\
  wget -O ruby-install-<%= ruby_install_version %>.tar.gz https://github.com/postmodern/ruby-install/archive/v<%= ruby_install_version %>.tar.gz &&\
  tar -xzvf ruby-install-<%= ruby_install_version %>.tar.gz &&\
  cd ruby-install-<%= ruby_install_version %>/ &&\
  make install

# Install latest MRI
RUN ruby-install ruby <%= ruby_version %>

# Set $PATH so that non-login shells will see the Ruby binaries
ENV PATH $PATH:/opt/rubies/ruby-<%= ruby_version %>/bin

# Add Ruby binaries to $PATH
ADD ./ruby.sh /etc/profile.d/ruby.sh
RUN chmod a+x /etc/profile.d/ruby.sh

# Never install Ruby docs
RUN echo "install: --no-rdoc --no-ri\nupdate: --no-rdoc --no-ri" > /etc/gemrc

# Install bundler gem
RUN /bin/bash -l -c 'gem install <%= gems.sort.join " " %>'

# Cleaning...
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

