ruby_version: 2.1.2
gems:
- bundler
packages:
- bison
- flex
- libxml2-dev
- libxslt1-dev
- libssl-dev
- libmagickwand-dev
- libreadline-dev
- zlib1g-dev
configure_options:
- --disable-install-doc
ruby_install_version: 0.4.3

